### ISSUE TITLE
When defining equations, store information about parents

### ISSUE THREAD

**Issue by schymans** [schymans/environmental-science-for-sagemath#2]
I can take an equation, e.g. `eq_Qi = Q_i == dT_i*lambda_i*A_i/L_i`, and solve it for another variable, e. g.:

`soln = solve(eq_Qi, dT_i)`

Then I can use the solution to define a new equation, eq_dTi_Qi as:
```
@register
class eq_dTi_Qi(Equation):
    """Temperature difference as a function of heat flux through wall.
    """
    expr = soln[0]
```
It would be nice if I could somehow store and later access the information that eq_dTi_Qi was derived from eq_Qi.

**Comment by jirikuncar** [comment]
Solved in 8101f26
