### ISSUE TITLE
Automatically import unit if NameError

### ISSUE THREAD

**Issue by schymans** [schymans/environmental-science-for-sagemath#3]
If I define a variable with units that have not been imported yet, a NameError is raised, e.g.:
`NameError: name 'kilogram' is not defined`

The remedy would be to first import `kilogram` by:

`from essm.variables.units import kilogram`

It would be good if this was done automatically.

 It would be good to intercept this and automatically import that

**Comment by jirikuncar** [comment]
Solved by using generator 3c513720062bd5312064f4e601a5403307d1faee
