### ISSUE TITLE
Enable and document inheritance between equations

### ISSUE THREAD

**Issue by schymans** [schymans/environmental-science-for-sagemath#34]
Previously, it was possible to define e.g. `eq_1` and then, based on `eq_1`, define `eq_2` in the way:
```python
class eq2(eq_1):
    """y as a function of x, based on eq_1."""
    expr: solve(eq_1, y)[0]
```
This does not seem to work any more, in the new sympy-based implementation.

**Comment by jirikuncar** [comment]
Have you tried: `class eq2(Equation, eq_1)`?

**Comment by schymans** [comment]
Unfortunately, this does not work either:
```python
/essm/equations/_core.pyc in __new__(cls, name, parents, dct)
    100 
    101             instance = super(EquationMeta, cls).__new__(
--> 102                 cls, name, parents, dct)
    103             expr = build_instance_expression(instance, expr)
    104             instance.expr = expr = BaseEquation(instance, expr)

TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by schymans** [comment]
The way it works is:
```python
class eq2(eq_1.definition):
     """Eq. 2 derived from Eq1."""
     expr = Eq(x, solve(eq_1, x, dict=True)[x])
```
Need to document it.

**Comment by schymans** [comment]
Now documented in a [jupyter notebook](https://github.com/environmentalscience/essm/blob/master/docs/examples/api_features.ipynb) and in the [documentation](https://essm.readthedocs.io/en/latest/examples/api_features.html#New-equation-based-on-manipulation-of-previous-equations).
